name: docker image build

on:
  push:
    paths-ignore:
      - LICENSE
      - setup.bash
      - README.md 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Clone this repository
        run: |
          cd ~/
          git clone -b mugimaru-2024 https://github.com/CIT-Autonomous-Robot-Lab/mugimaru-docker.git
      - name: Clone requirements packages
        run: |
          cd ~/mugimaru-docker/
          ./test/install_packages.bash
      - name: Docker image build
        run: |
          ./build.sh
